version: "3.8"
services:
  course-db:
    image: mongo
    restart: always
    container_name: ms-computer-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: computers
    volumes:
      - ms-computer-db-data:/data/db
volumes:
  ms-computer-db-data: