spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27018/computers?authSource=admin
      database: computers
springdoc:
  swagger-ui:
    path: /api-docs
server:
  port: 8081