spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/computers?authSource=admin
      database: computers
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      port: 35730
springdoc:
  swagger-ui:
    path: '/api/computers/docs'
  api-docs:
    path: '/api/computers/docs'
server:
  port: 8081
management:
  endpoints:
    jmx:
      exposure:
        include: 'health,info'
    web:
      base-path: '/api/computers/status'
      path-mapping:
        health: /health