spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@admiralis-db:27017/computers?authSource=admin
      database: computers
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      port: 35730
springdoc:
  swagger-ui:
    path: /api-docs
server:
  port: 8081