spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@admiralis-db:27017/computers?authSource=admin
      database: computers
springdoc:
  swagger-ui:
    path: '/api/computers/docs'
  api-docs:
    path: '/api/computers/docs'
server:
  port: 80
management:
  endpoints:
    jmx:
      exposure:
        include: 'health,info'
    web:
      base-path: '/api/computers/status'
      path-mapping:
        health: /health